export const INSURANCE_PANELS = [
  'Aetna',
  'Ambetter',
  'AmeriHealth',
  'Anthem',
  'Beacon Health Options / Carelon',
  'Blue Cross Blue Shield (BCBS)',
  'BCBS of Alabama',
  'BCBS of Arizona',
  'BCBS of California',
  'BCBS of Florida',
  'BCBS of Georgia',
  'BCBS of Illinois',
  'BCBS of Michigan',
  'BCBS of New Jersey',
  'BCBS of New York',
  'BCBS of North Carolina',
  'BCBS of Texas',
  'Bright Health',
  'CareFirst',
  'Centene',
  'Cigna',
  'Community Health Plan',
  'Fidelis Care',
  'Florida Blue',
  'Harvard Pilgrim',
  'Highmark',
  'HealthFirst',
  'Humana',
  'Independence Blue Cross',
  'Kaiser Permanente',
  'Magellan Health',
  'Medicaid',
  'Medicare',
  'Molina Healthcare',
  'MVP Health Care',
  'Optum',
  'Oscar Health',
  'Providence Health Plan',
  'Regence',
  'TriCare',
  'Tufts Health Plan',
  'UnitedHealthcare (UHC)',
  'UPMC Health Plan',
  'ValueOptions',
  'WellCare',
];

export const ABA_CERTIFICATIONS = [
  // Clinical credentials
  'RBT – Registered Behavior Technician',
  'BCaBA – Board Certified Assistant Behavior Analyst',
  'BCBA – Board Certified Behavior Analyst',
  'BCBA-D – Doctoral Board Certified Behavior Analyst',
  // Safety / crisis
  'CPR/First Aid (AHA)',
  'CPR/First Aid (Red Cross)',
  'CPI – Crisis Prevention Institute (NVCI)',
  'Safety Care (QBS)',
  'PROACT – Professional Management of Disruptive Behavior',
  'MANDT System',
  'Handle With Care',
  'Therapeutic Crisis Intervention (TCI)',
  'Seizure First Aid',
  // Assessment
  'VB-MAPP Trained Assessor',
  'ABLLS-R Training',
  'ADOS-2 Training',
  // Compliance
  'Mandated Reporter Training',
  'HIPAA Certification',
  'Bloodborne Pathogens',
  // Therapy methods
  'Discrete Trial Training (DTT)',
  'Natural Environment Teaching (NET)',
  'Verbal Behavior (VB) Training',
  'Positive Behavior Support (PBS)',
  'Functional Behavior Assessment (FBA)',
];
